# Generated by Django 5.0.1 on 2024-01-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_background_color', models.CharField(default='#ffffff', max_length=20)),
                ('navbar_background_color', models.CharField(default='#343a40', max_length=20)),
                ('footer_background_color', models.CharField(default='#343a40', max_length=20)),
            ],
        ),
    ]
