# Generated by Django 5.0.1 on 2024-01-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_remove_config_footer_background_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='home_text_paragraph',
            field=models.TextField(default='Market, news, trade, analyse, bots and much more ..'),
        ),
        migrations.AlterField(
            model_name='config',
            name='home_text_subtitle',
            field=models.CharField(default='Everything you need to crack the market', max_length=255),
        ),
        migrations.AlterField(
            model_name='config',
            name='home_text_title',
            field=models.CharField(default='CryptoKilla', max_length=255),
        ),
    ]
