# Generated by Django 5.0.1 on 2024-01-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_alter_config_home_text_paragraph_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='background_image_url',
            field=models.CharField(default='url("header-backgroud.jpg")', max_length=100),
        ),
        migrations.AlterField(
            model_name='config',
            name='home_image_prosition',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center'), ('none', 'None')], default='left', max_length=10),
        ),
    ]
