# Generated by Django 5.0.1 on 2024-01-28 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_alter_config_background_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='home_image_url',
            field=models.URLField(default='https://placehold.co/600x400'),
        ),
    ]
