# Generated by Django 5.0.1 on 2024-01-29 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_alter_config_home_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='sections_features_list',
            field=models.JSONField(default=[{'body_text': 'Default body text 1', 'image_url': 'default_image_url1'}, {'body_text': 'Default body text 2', 'image_url': 'default_image_url2'}]),
        ),
    ]
